update scripts

diff --git a/general/.bin/tldr b/general/.bin/tldr
--- a/general/.bin/tldr
+++ b/general/.bin/tldr
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # tldr client by Ray Lee, http://github.com/raylee/tldr
 # a Sunday afternoon's project, I'm sure there's room for improvement. PRs welcome!
 
@@ -72,29 +72,29 @@ style_for() {
 # function contents via http://mywiki.wooledge.org/BashFAQ/037
 init_term_cmds() {
     true && {
-        reset=$(    tput sgr0   || tput me      ) # Reset cursor
-        bold=$(     tput bold   || tput md      ) # Start bold
-        underline=$(tput smul   || tput us      ) # Start underline
-        italic=$(   tput sitm   || tput ZH      ) # Start italic
-        eitalic=$(  tput ritm   || tput ZH      ) # End italic
-        default=$(  tput op                     )
-        back=$(     printf '\b' )
+        reset=$(tput sgr0 || tput me)     # Reset cursor
+        bold=$(tput bold || tput md)      # Start bold
+        underline=$(tput smul || tput us) # Start underline
+        italic=$(tput sitm || tput ZH)    # Start italic
+        eitalic=$(tput ritm || tput ZH)   # End italic
+        default=$(tput op)
+        back=$(printf '\b')
 
         case "$TERM" in
-            *-m) ;;
-            *)
-                black=$(    tput setaf 0 || tput AF 0    )
-                red=$(      tput setaf 1 || tput AF 1    )
-                green=$(    tput setaf 2 || tput AF 2    )
-                yellow=$(   tput setaf 3 || tput AF 3    )
-                blue=$(     tput setaf 4 || tput AF 4    )
-                magenta=$(  tput setaf 5 || tput AF 5    )
-                cyan=$(     tput setaf 6 || tput AF 6    )
-                white=$(    tput setaf 7 || tput AF 7    )
+        *-m) ;;
+        *)
+            black=$(tput setaf 0 || tput AF 0)
+            red=$(tput setaf 1 || tput AF 1)
+            green=$(tput setaf 2 || tput AF 2)
+            yellow=$(tput setaf 3 || tput AF 3)
+            blue=$(tput setaf 4 || tput AF 4)
+            magenta=$(tput setaf 5 || tput AF 5)
+            cyan=$(tput setaf 6 || tput AF 6)
+            white=$(tput setaf 7 || tput AF 7)
 
-                onblue=$(   tput setab 4 || tput AB 4    )
-                ongrey=$(   tput setab 7 || tput AB 7    )
-                ;;
+            onblue=$(tput setab 4 || tput AB 4)
+            ongrey=$(tput setab 7 || tput AB 7)
+            ;;
         esac
     } 2>/dev/null
 
@@ -167,26 +167,26 @@ display_tldr() {
         [ -z "$trimmed" ] && [ "$last_token" = "list_item" ] && continue
 
         case "$line" in
-            \#*)
-                heading "$line"
-                last_token="heading"
-                ;;
-            \>*)
-                quotation "$line"
-                last_token="quotation"
-                ;;
-            -*)
-                list_item "$line"
-                last_token="list_item"
-                ;;
-            \`*)
-                code "$line"
-                last_token="code"
-                ;;
-            *)
-                text "$line"
-                last_token="text"
-                ;;
+        \#*)
+            heading "$line"
+            last_token="heading"
+            ;;
+        \>*)
+            quotation "$line"
+            last_token="quotation"
+            ;;
+        -*)
+            list_item "$line"
+            last_token="list_item"
+            ;;
+        \`*)
+            code "$line"
+            last_token="code"
+            ;;
+        *)
+            text "$line"
+            last_token="text"
+            ;;
         esac
     done
 }
@@ -194,11 +194,11 @@ display_tldr() {
 # convert the local platorm name to tldr's version
 get_platform() {
     case $(uname -s) in
-        Darwin)                 echo "osx"    ;;
-        Linux)                  echo "linux"  ;;
-        SunOS)                  echo "sunos"  ;;
-        CYGWIN*|MINGW32*|MSYS*) echo "windows" ;;
-        *)                      echo "common" ;;
+    Darwin) echo "osx" ;;
+    Linux) echo "linux" ;;
+    SunOS) echo "sunos" ;;
+    CYGWIN* | MINGW32* | MSYS*) echo "windows" ;;
+    *) echo "common" ;;
     esac
 }
 
@@ -211,7 +211,7 @@ path_for_cmd() {
     fi
 
     # results in, eg, "name":"netstat","platform":["linux","osx"]},
-    desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
+    desc=$(tr '{' '\n' <$index | grep "\"name\":\"$1\"")
     [ -z "$desc" ] && echo "-- not found --" && return
 
     # use the platform specific version of the tldr first
@@ -222,7 +222,7 @@ path_for_cmd() {
     else
         # take the first one so we can show something, but warn the user
         p=$(echo "$desc" | cut -d '"' -f 8)
-        >&2 printf "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
+        printf >&2 "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
         echo "$p/$1.md"
     fi
 }
@@ -230,8 +230,8 @@ path_for_cmd() {
 # cache a local copy of the tldrpage
 cache_tldr() {
     contains "$(tar --version | head -n 1)" bsdtar || taropt='--wildcards --overwrite'
-    curl -sfL https://github.com/tldr-pages/tldr/tarball/master \
-    | tar xzf - --strip-components=2 -C "$configdir" ${taropt-} '*/pages/'
+    curl -sfL https://github.com/tldr-pages/tldr/tarball/master |
+        tar xzf - --strip-components=2 -C "$configdir" ${taropt-} '*/pages/'
     update_index
 }
 
@@ -248,12 +248,12 @@ get_tldr() {
 }
 
 fetch_tldr() {
-    curl -sf "https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/{$platform,common}/$1.md"
+    curl -sf "$base_url/{$platform,common}/$1.md"
 }
 
 list_pages() {
-    for platform in $(ls "$configdir" ); do
-        for page in $(ls 2>/dev/null "$configdir"/"$platform/") ; do
+    for platform in $(ls "$configdir"); do
+        for page in $(ls 2>/dev/null "$configdir"/"$platform/"); do
             bname "$page" .md
         done
     done | sort | uniq
@@ -279,38 +279,37 @@ The client caches a copy of all pages and the index locally under
 $configdir . By default, the cached copies will expire in $cache_days days.
 
 EOF
-exit 0
+    exit 0
 }
 
-while [ $# -gt 0 ]
-do
+while [ $# -gt 0 ]; do
     case "$1" in
-        -l|--list)
-            >&2 printf "Known tldr pages: \n"
-            list_pages
-            exit 0
-            ;;
-        -n)
-            TLDR_CACHE=no
-            ;;
-        -p|--platform)
-            shift
-            platform=$1
-            ;;
-        -u|-c|--cache|--update)
-            cache_tldr
-            exit 0
-            ;;
-        -h|-\?|--help|-*)
-            usage
-            ;;
-        *)
-            # there are pages with hypens in them, such as git-tag. The below converts
-            # `tldr git tag` to the hyphenated version
-            hyphenated=$(printf %s "$*" | tr ' ' '-')
-            page=${hyphenated:-''}
-            break
-            ;;
+    -l | --list)
+        printf >&2 "Known tldr pages: \n"
+        list_pages
+        exit 0
+        ;;
+    -n)
+        TLDR_CACHE=no
+        ;;
+    -p | --platform)
+        shift
+        platform=$1
+        ;;
+    -u | -c | --cache | --update)
+        cache_tldr
+        exit 0
+        ;;
+    -h | -\? | --help | -*)
+        usage
+        ;;
+    *)
+        # there are pages with hypens in them, such as git-tag. The below converts
+        # `tldr git tag` to the hyphenated version
+        hyphenated=$(printf %s "$*" | tr ' ' '-')
+        page=${hyphenated:-''}
+        break
+        ;;
     esac
     shift
 done
